### PR TITLE
add validation result value to req.body

### PR DESCRIPTION
**Pull request by zhaoyao91**
joi not only validate the values, it also convert the values into the proper type. we can leverage it and make our life easier.

### CODE REVIEW

**Comment by stearm** [comment]
@zhaoyao91 yes, you're right. Can you just write some tests to keep coverage? Thank you!

**Comment by zhaoyao91** [comment]
I have added a test without trying it.

**Comment by zhaoyao91** [comment]
hi, I have added the test to this pr, and it passed

**Comment by zhaoyao91** [comment]
This is expected. Note the difference:
- the req.body has the field with correct type since it's processed by joi
- the body from await json(req) has the string field since it's just string as passed in

**Pull request merged**
